# This workflow builds sphinx documentation and deploys static html files to GitHub Pages.

name: Documentation

on:
  push:
    branches:
      - master
      - docs

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python3 -m pip install ".[docs]"

      - name: Install pandoc
        run: sudo apt-get -y install pandoc

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Build documentation
        run: |
          cd ./doc/sphinx
          make html-multiversion
          cp _assets/gh-pages-redirect.html _build/index.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./doc/sphinx/_build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
